-- Task 4 ke liye PRODUCTS table banana
-- Is file ko sirf ek baar run karna hai

CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100)
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME)
VALUES (1, 'Laptop');

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME)
VALUES (2, 'Smartphone');

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME)
VALUES (3, 'Headphones');

COMMIT;

SELECT * FROM PRODUCTS;
