CREATE DATABASE IF NOT EXISTS InstaClone;
USE InstaClone;
CREATE TABLE IF NOT EXISTS Users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    followers_count INT DEFAULT 0
);
